### ISSUE TITLE
Points lost at logout!

### ISSUE THREAD

**Issue by jarvil1** [h5p/h5p-summary#68]
Hello,

There seems to be a bug in summary-question, if you logout after completing the activity you lose poiints you have gained from it. See attached video, originsal h5p is also attached for testing purposes.

Tested on 

- Moodle 3.9.12
- mod_hvp 1.22.4
- h5p save state set on
- Summary (1.10.11) 

@fnoks 

[template-592.zip](https://github.com/h5p/h5p-summary/files/8284406/template-592.zip)

https://user-images.githubusercontent.com/53904029/158801914-fd0ed1e2-fd59-4bf9-979f-36fe17d9de47.mp4

**Comment by otacke** [comment]
Fixed in https://github.com/h5p/h5p-summary/pull/69

**Comment by Urpokarhu1** [comment]
Hello @otacke ,

This bug is still present at 04.10.2024 and you lose points at page refresh. Tested on https://h5p.org with https://h5p.org/presentation and Moodle 4.1 & mod_hvp 1.26 see attached video

https://github.com/user-attachments/assets/1935daf9-befa-446e-99e2-09492cfdf3d5

**Comment by otacke** [comment]
@Urpokarhu1 On h5p.org, the previous state is not stored at all 😉
